jwt:
  public:
    key: 'classpath:app.pub'
  private:
    key: 'classpath:app.key'
spring:
  application:
    name: 'AuthService'
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/users_commerce}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true